Repository paketo-buildpacks/pipeline-builder, pull requests merged in 2021-11, with the labels that each got.

#441 Change the way Java stackdriver version is being represented
  actions/google-stackdriver-profiler-dependency/main.go
Labels: type:bug, semver:patch

#446 Improves integration with Foojay API
  actions/foojay-dependency/main.go
Labels: type:bug, semver:patch

#448 Fixes typo that caused non-stable releases to be selected
  actions/clojure-tools-dependency/main.go
Labels: type:bug, semver:patch

#449 Sends a user agent with requests to the Foojay API
  actions/foojay-dependency/main.go
Labels: type:task, semver:patch

#451 Add a tool and workflow for republishing images with different ids
  README.md
  buildpack/helpers.go
  buildpack/images.go
  buildpack/rewriteLayer.go
  cmd/update-buildpack-image-id/main.go
  go.mod
  go.sum
  octo/check-republish-version.sh
  octo/descriptor.go
  octo/install-update-buildpack-image-id.sh
  octo/lite_packages.go
  octo/octo.go
  octo/republish-image.sh
  octo/statik/statik.go
Labels: type:enhancement, semver:minor

#453 Fixes bug where name and website were being stripped from the metadata when updating the buildpack metadata labels
  buildpack/images.go
Labels: type:bug, semver:patch

#456 Adds flag to update the version
  buildpack/images.go
  buildpack/rewriteLayer.go
  cmd/update-buildpack-image-id/main.go
Labels: type:enhancement, semver:minor

#459 Modifies republish workflow to also change versions
  go.mod
  go.sum
  octo/check-republish-version.sh
  octo/lite_packages.go
  octo/republish-image.sh
  octo/statik/statik.go
Labels: type:enhancement, semver:minor

#460 Modifies the republish workflow to accept a target_repo setting
  README.md
  octo/descriptor.go
  octo/lite_packages.go
  octo/statik/statik.go
Labels: type:bug, semver:patch

#482 Bump transitive deps
  go.mod
  go.sum
Labels: type:dependency-upgrade, semver:patch

#480 Only rewrite layers with matching id and version
  buildpack/images.go
Labels: type:bug, semver:patch
