Repository paketo-buildpacks/pipeline-builder, pull requests merged in 2022-04, with the labels that each got.

#612 Added logic to handle multiple repositories for publishing
  README.md
  octo/create_package.go
  octo/descriptor.go
  octo/package-buildpack.sh
  octo/statik/statik.go
  octo/test.go
Labels: type:enhancement, semver:minor

#624 Fixes two panics
  README.md
  octo/create_package.go
  octo/descriptor.go
  octo/test.go
Labels: type:bug, semver:patch

#630 Add an action to update draft release notes
  .github/pipeline-descriptor.yml
  .github/workflows/create-action-draft-release.yml
  .github/workflows/tests.yml
  actions/action.go
  actions/draft-release/draft.template
  actions/draft-release/main.go
  drafts/drafts.go
  drafts/drafts_test.go
  drafts/init_test.go
  drafts/mocks/buildpack_loader.go
  drafts/testdata/builder/builder.toml
  drafts/testdata/component-no-deps/buildpack.toml
  drafts/testdata/component/buildpack.toml
  drafts/testdata/composite/buildpack.toml
  drafts/testdata/composite/package.toml
  go.mod
  go.sum
  integration/drafts_test.go
  integration/init_test.go
  octo/draft_release.go
  octo/statik/statik.go
  octo/update-draft-release-buildpack.sh
Labels: type:task, semver:patch

#632 Bump actions to latest major version
  octo/builder_dependencies.go
  octo/buildpack_dependencies.go
  octo/create_builder.go
  octo/create_package.go
  octo/draft_release.go
  octo/lite_packages.go
  octo/offline_packages.go
  octo/package_dependencies.go
  octo/test.go
  octo/update_pipeline.go
Labels: type:task, semver:patch

#633 Don't use Tempdir with system default
  actions/draft-release/main.go
  drafts/drafts.go
Labels: type:bug, semver:patch

#634 Switch action to use Github library
  actions/alibaba-dragonwell-dependency/main.go
  actions/amazon-corretto-dependency/main.go
  actions/clojure-tools-dependency/main.go
  actions/draft-release/main.go
  actions/github-release-dependency/main.go
  actions/graalvm-dependency/main.go
  actions/ibm-semeru-dependency/main.go
  actions/leiningen-dependency/main.go
  actions/rustup-init-dependency/main.go
  go.mod
  go.sum
Labels: type:task, semver:patch

#635 Remove unnecessary jobs in update draft release
  actions/draft-release/main.go
  octo/draft_release.go
Labels: type:task, semver:patch

#636 Adds debugging
  actions/draft-release/main.go
Labels: type:task, semver:patch

#637 Catches missed error handling
  actions/draft-release/main.go
Labels: type:bug, semver:patch

#638 Removes additional debug info
  actions/draft-release/main.go
Labels: type:task, semver:patch

#639 Create tempdir if not using the default
  drafts/drafts.go
Labels: type:bug, semver:patch

#640 Add /tmp to container
  actions/Dockerfile
  drafts/drafts.go
Labels: type:bug, semver:patch

#641 Adds auth for connecting to non-public gcr.io registries
  drafts/drafts.go
Labels: type:task, semver:patch

#642 Force draft-release to rebuild
  actions/draft-release/main.go
Labels: type:task, semver:patch

#644 Adds a Github buildpack loader
  README.md
  actions/draft-release/draft.template
  actions/draft-release/main.go
  drafts/drafts.go
  drafts/drafts_test.go
  drafts/testdata/builder/builder.toml
  go.mod
  go.sum
  integration/drafts_test.go
  octo/draft_release.go
Labels: type:task, semver:patch

#645 Pull in a GCR service key from input
  drafts/drafts.go
Labels: type:task, semver:patch

#646 Add additional logging to draft updater
  drafts/drafts.go
Labels: type:task, semver:patch

#648 Moves config into descriptor
  README.md
  actions/draft-release/main.go
  octo/descriptor.go
  octo/draft_release.go
Labels: type:task, semver:patch

#649 Fix loading version
  actions/draft-release/main.go
  drafts/drafts.go
  integration/drafts_test.go
Labels: type:bug, semver:patch

#650 Sort information for draft release output
  actions/draft-release/main.go
  drafts/drafts.go
  drafts/drafts_test.go
  drafts/testdata/component/buildpack.toml
  integration/drafts_test.go
Labels: type:task, semver:patch

#651 Adds compute-artifact-description action
  .github/pipeline-descriptor.yml
  .github/workflows/create-action-compute-artifact-description.yml
  .github/workflows/tests.yml
  .github/workflows/update-pipeline.yml
  actions/compute-artifact-description/main.go
  drafts/drafts.go
Labels: type:task, semver:patch

#653 Add version to compute artifact action
  README.md
  actions/compute-artifact-description/main.go
Labels: type:task, semver:patch

#654 Fixes bug in compute-artifact-description
  actions/compute-artifact-description/main.go
Labels: type:bug, semver:patch
