Repository paketo-buildpacks/pipeline-builder, pull requests merged in 2022-03, with the labels that each got.

#581 Add separate CPE & PURL version
  actions/liberty-dependency/main.go
Labels: type:bug, semver:patch

#584 Bump dependencies
  go.mod
  go.sum
Labels: type:dependency-upgrade, semver:patch

#586 Maintenance updates to CI
  .github/workflows/create-action-adoptium-dependency.yml
  .github/workflows/create-action-alibaba-dragonwell-dependency.yml
  .github/workflows/create-action-amazon-corretto-dependency.yml
  .github/workflows/create-action-appdynamics-dependency.yml
  .github/workflows/create-action-aqua-security-dependency.yml
  .github/workflows/create-action-aternity-dependency.yml
  .github/workflows/create-action-azul-zulu-dependency.yml
  .github/workflows/create-action-bellsoft-liberica-dependency.yml
  .github/workflows/create-action-ca-apm-dependency.yml
  .github/workflows/create-action-cf-java-index-dependency.yml
  .github/workflows/create-action-clojure-tools-dependency.yml
  .github/workflows/create-action-foojay-dependency.yml
  .github/workflows/create-action-gcs-dependency.yml
  .github/workflows/create-action-github-release-dependency.yml
  .github/workflows/create-action-google-stackdriver-profiler-dependency.yml
  .github/workflows/create-action-graalvm-dependency.yml
  .github/workflows/create-action-gradle-dependency.yml
  .github/workflows/create-action-ibm-semeru-dependency.yml
  .github/workflows/create-action-jprofiler-dependency.yml
  .github/workflows/create-action-jrebel-dependency.yml
  .github/workflows/create-action-leiningen-dependency.yml
  .github/workflows/create-action-liberty-dependency.yml
  .github/workflows/create-action-maven-dependency.yml
  .github/workflows/create-action-new-relic-dependency.yml
  .github/workflows/create-action-npm-dependency.yml
  .github/workflows/create-action-overops-dependency.yml
  .github/workflows/create-action-paketo-deps-dependency.yml
  .github/workflows/create-action-rustup-init-dependency.yml
  .github/workflows/create-action-skywalking-dependency.yml
  .github/workflows/create-action-spring-generations.yml
  .github/workflows/create-action-tomcat-dependency.yml
  .github/workflows/create-action-tomee-dependency.yml
  .github/workflows/create-action-yourkit-dependency.yml
  .github/workflows/synchronize-labels.yml
  .github/workflows/tests.yml
  .github/workflows/update-pipeline.yml
  octo/actions.go
  octo/builder_dependencies.go
  octo/buildpack_dependencies.go
  octo/create_builder.go
  octo/create_package.go
  octo/draft_release.go
  octo/labels.go
  octo/lite_packages.go
  octo/offline_packages.go
  octo/package_dependencies.go
  octo/statik/statik.go
  octo/test.go
  octo/update_pipeline.go
Labels: type:task, semver:patch

#592 Add tomee-dependency to pipeline-descriptor
  .github/pipeline-descriptor.yml
Labels: type:enhancement, semver:patch

#578 Add a separate pipeline for integration tests if `integration/*.go` exists
  go.mod
  go.sum
  octo/init_test.go
  octo/run-integration-tests.sh
  octo/run-unit-tests.sh
  octo/statik/statik.go
  octo/test.go
  octo/test_test.go
Labels: type:enhancement, semver:minor
