Repository paketo-buildpacks/pipeline-builder, pull requests merged in 2022-02, with the labels that each got.

#535 Update Foojay action to filter by libc type
  actions/foojay-dependency/main.go
Labels: type:task, semver:patch

#540 Update GraalVM action to handle new Graal CE build version
  actions/graalvm-dependency/main.go
Labels: type:bug, semver:patch

#542 Enable package and offline_package to support nested project structures
  README.md
  octo/create-package.sh
  octo/descriptor.go
  octo/offline_packages.go
  octo/statik/statik.go
Labels: type:enhancement, semver:minor

#546 Add a tomee-dependency action to track apache-tomee
  .github/workflows/create-action-tomee-dependency.yml
  README.md
  actions/action.go
  actions/tomee-dependency/main.go
Labels: type:enhancement, semver:minor

#543 Add tag filtering for offline_packages and republish_images
  README.md
  octo/check-republish-version.sh
  octo/checkout-next-version.sh
  octo/descriptor.go
  octo/lite_packages.go
  octo/offline_packages.go
  octo/statik/statik.go
Labels: type:enhancement, semver:minor

#548 Add missing `SOURCE_PATH` for `package`
  README.md
  octo/create_package.go
  octo/descriptor.go
Labels: type:bug, semver:patch

#547 Switch to using new Apache download mirror
  README.md
  actions/skywalking-dependency/main.go
  actions/tomee-dependency/main.go
Labels: type:task, semver:patch

#549 Revert version format change
  actions/action.go
Labels: type:bug, semver:patch

#555 Fix check-republish-version
  octo/check-republish-version.sh
  octo/statik/statik.go
Labels: type:bug, semver:patch

#557 Updated regex for matching unzipped JDK dir
  actions/alibaba-dragonwell-dependency/main.go
Labels: type:bug, semver:patch

#559 Bump golang to 1.17 & other tool versions
  go.mod
  octo/octo.go
Labels: type:dependency-upgrade, semver:patch

#560 Renamed Riverbed action to Aternity
  .github/pipeline-descriptor.yml
  .github/workflows/create-action-aternity-dependency.yml
  README.md
  actions/aternity-dependency/main.go
Labels: type:enhancement, semver:patch

#563 Updated bellsoft action to set purl to NIK version
  actions/bellsoft-liberica-dependency/main.go
Labels: type:bug, semver:patch

#573 add liberty action
  README.md
  actions/liberty-dependency/main.go
Labels: type:enhancement, semver:minor

#575 Add CI for creating liberty action
  .github/pipeline-descriptor.yml
  .github/workflows/create-action-liberty-dependency.yml
Labels: type:enhancement, semver:minor

#576 Updates copyright year
  actions/liberty-dependency/main.go
Labels: type:task, semver:patch
