Repository paketo-buildpacks/pipeline-builder, pull requests merged in 2023-10, with the labels that each got.

#1300 Issue #111: Adoptium actions adds source
  actions/adoptium-dependency/main.go
Labels: type:enhancement, semver:minor

#1319 Updates the rust action to include source/source_sha information
  actions/rust-dependency/main.go
  actions/rustup-init-dependency/main.go
  go.mod
  go.sum
Labels: type:enhancement, semver:minor

#1320 Issue #111: Bellsoft Liberica actions adds source
  actions/bellsoft-liberica-dependency/main.go
Labels: type:enhancement, semver:minor

#1325 updates actions with source output, fixes bug
  actions/github-release-dependency/main.go
  actions/gradle-dependency/main.go
  actions/ibm-semeru-dependency/main.go
  actions/leiningen-dependency/main.go
  actions/liberty-dependency/main.go
  actions/maven-dependency/main.go
  actions/new-relic-dependency/main.go
  actions/npm-dependency/main.go
  actions/skywalking-dependency/main.go
  actions/tomcat-dependency/main.go
  actions/tomee-dependency/main.go
Labels: type:enhancement, semver:minor

#1322 Issue #111: Amazon Corretto actions adds source
  actions/amazon-corretto-dependency/main.go
Labels: type:enhancement, semver:minor

#1321 Issue #111: Alibaba DragonWell actions adds source
  actions/alibaba-dragonwell-dependency/main.go
Labels: type:enhancement, semver:minor

#1331 Specify proper bundle type for Bellsoft
  actions/bellsoft-liberica-dependency/main.go
Labels: type:bug, semver:patch

#1334 Issue #111: Clojure action adds source
  actions/clojure-tools-dependency/main.go
Labels: type:enhancement, semver:patch

#1337 Issue #111: no source for JRE
  actions/bellsoft-liberica-dependency/main.go
Labels: type:enhancement, semver:patch
