Repository paketo-buildpacks/pipeline-builder, pull requests merged in 2023-06, with the labels that each got.

#1168 Switch to using Azul Metadata API
  actions/azul-zulu-dependency/main.go
Labels: type:enhancement, semver:minor

#1184 Add dotnet new-relic agent support
  actions/new-relic-dependency/main.go
Labels: type:enhancement, semver:patch

#1195 Change `go get -u` to fetch minor/patch updates
  .github/workflows/pb-update-go.yml
  octo/statik/statik.go
  octo/update-go.sh
Labels: type:bug, semver:patch
