Repository paketo-buildpacks/pipeline-builder, pull requests merged in 2024-05, with the labels that each got.

#1587 Simplify integration tests
  octo/package-buildpack.sh
  octo/run-integration-tests.sh
  octo/statik/statik.go
  octo/test.go
  octo/test_test.go
Labels: type:enhancement, semver:minor

#1611 Restore missing integration tests
  .github/workflows/pb-tests.yml
  octo/test.go
  octo/test_test.go
Labels: type:bug, semver:patch

#1616 Update to Go 1.22
  octo/octo.go
Labels: type:dependency-upgrade, semver:minor

#1620 Add ARM64 update support for YourKit updater
  actions/yourkit-dependency/main.go
Labels: type:enhancement, semver:minor

#1622 Convert to the arch used by the API within the action
  actions/yourkit-dependency/main.go
Labels: type:bug, semver:patch
