Repository paketo-buildpacks/pipeline-builder, pull requests merged in 2024-03, with the labels that each got.

#1508 Remove old version number
  octo/create_package.go
Labels: type:dependency-upgrade, semver:patch

#1520 Use pack experimental
  octo/create_package.go
  octo/install-experimental-pack.sh
  octo/package-buildpack.sh
  octo/statik/statik.go
Labels: type:enhancement, semver:minor

#1524 Use pack experimental
  octo/package-buildpack.sh
  octo/statik/statik.go
Labels: type:bug, semver:patch

#1535 Fix bellsoft liberica NIK retrieval
  actions/bellsoft-liberica-dependency/main.go
Labels: type:bug, semver:patch

#1526 Control build.sh and .gitignore
  drafts/mocks/buildpack_loader.go
  octo/build-script.sh
  octo/descriptor.go
  octo/git.go
  octo/octo.go
  octo/scripts.go
  octo/statik/statik.go
Labels: type:enhancement, semver:minor

#1539 Fix update-pipeline
  octo/statik/statik.go
  octo/update-pipeline.sh
Labels: type:bug, semver:patch

#1540 Fix package test
  octo/statik/statik.go
  octo/test.go
Labels: type:enhancement, semver:patch
